[2022-07-26T10:43:47] WARNING [django.request.log_response:224] Not Found: /favicon.ico/
[2022-07-26T10:43:50] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T10:44:35] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T11:49:22] INFO [root.logout:150] admin_ logged out
[2022-07-26T11:49:26] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T11:50:21] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T11:50:22] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T11:50:22] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T11:50:22] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:07:45] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:07:48] ERROR [django.request.log_response:224] Internal Server Error: /apps/all/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\saketh\Documents\billapp\apps\views.py", line 42, in showapps
    return render(request,'showapps.html',{'showapp':appli,'leni':leni,'msg':mssg})
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 10: 'static'. Did you forget to register or load this tag?
[2022-07-26T12:08:03] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:08:03] ERROR [django.request.log_response:224] Internal Server Error: /apps/all/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\saketh\Documents\billapp\apps\views.py", line 42, in showapps
    return render(request,'showapps.html',{'showapp':appli,'leni':leni,'msg':mssg})
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 968, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 817, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 57: 'else', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
[2022-07-26T12:08:48] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:09:09] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:09:19] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:09:21] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:09:34] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:09:35] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:09:35] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:09:35] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:09:35] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:09:44] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:09:54] INFO [root.addapp:30] admin_added an app
[2022-07-26T12:09:54] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:10:16] INFO [root.showapps:41] admin_seen the whole applist
[2022-07-26T12:10:27] INFO [root.showapps:41] admin_seen the whole applist
